services:
  - type: web
    name: sigue-tu-estrella-api
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
